FROM fedora:25

RUN dnf install -y https://developer.download.nvidia.com/compute/cuda/repos/fedora25/x86_64/cuda-repo-fedora25-9.1.85-1.x86_64.rpm
RUN dnf install -y cuda-core-9-0 cuda-cudart-dev-9-0 cuda-cufft-dev-9-0 cuda-cublas-dev-9-0 git armadillo-devel boost-openmpi-devel cmake make openmpi-devel
ENV PATH="/usr/lib64/openmpi/bin/:/usr/local/cuda-9.0/bin/:${PATH}"

RUN git clone --recurse https://pisto@bitbucket.org/pisto/nlchains.git /tmp/nlchains
RUN mkdir /tmp/nlchains/build
WORKDIR /tmp/nlchains/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_FLAGS="-gencode arch=compute_35,code=sm_35 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70" -Doptimized_chain_length=64 /tmp/nlchains
RUN make -j
RUN cp nlchains /usr/bin/nlchains
